#!/usr/bin/env bash
#
# Copyright © 2023 Kizziama <kizziama@proton.me>
#
# SPDX-License-Identifier: Apache-2.0
#

set -e

# Git identity
GIT_USER="Kizziama"
GIT_EMAIL="kizziama@proton.me"
git config --global user.name "$GIT_USER"
git config --global user.email "$GIT_EMAIL"

# Git alias
git config --global alias.c "commit -s"
git config --global alias.cam "commit --am"
git config --global alias.cm "commit"
git config --global alias.csm "commit -s -m"
git config --global alias.ca "cherry-pick --abort"
git config --global alias.cr "cherry-pick --signoff"
git config --global alias.p "push -f"
git config --global alias.cc "cherry-pick --continue"
git config --global alias.cs "cherry-pick --skip"
git config --global alias.cp "cherry-pick"
git config --global alias.r "revert"
git config --global alias.rc "revert --continue"
git config --global alias.ro "remote rm origin"
git config --global alias.ra "remote add origin"
git config --global alias.s "switch -c"
git config --global alias.b "branch"
git config --global alias.rh "reset --hard"
git config --global alias.ch "checkout"
git config --global alias.f "fetch"
git config --global alias.m "merge"

# Change-id hooks
mkdir -p ~/.git/hooks
git config --global core.hooksPath ~/.git/hooks
curl -Lo ~/.git/hooks/commit-msg http://review.lineageos.org/tools/hooks/commit-msg
chmod a+x ~/.git/hooks/commit-msg

# Git credentials
if [ "$1" == "creds" ]; then
	if [ ! -f "~/.git-credentials" ]; then
		echo "[!] Enter your git token"
		read git_token
		GIT_TOKEN="$git_token"
		echo "https://$GIT_USER:$GIT_TOKEN@github.com" >~/.git-credentials
		git config --global credential.helper "store --file ~/.git-credentials"
	fi
fi
